// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kfcvhmnwdemobokkinvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmY3ZobW53ZGVtb2Jva2tpbnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjQwMDQsImV4cCI6MjA3MzkwMDAwNH0.zU6sRLrkon-_t7HY6GAaxYA9xadHJDNXl75xthL4h7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);